export const categoryOptions = [
  {text: 'Auto, Boat & Air', value: 'auto-boat-and-air'},
  {text: 'Business & Professional', value: 'business-and-professional'},
  {text: 'Charity & Causes', value: 'charity-and-causes'},
  {text: 'Comedy', value: 'comedy'},
  {text: 'Community & Culture', value: 'community-and-culture'},
  {text: 'Dance', value: 'dance'},
  {text: 'Education', value: 'education'},
  {text: 'Family', value: 'family'},
  {text: 'Fashion & Beauty', value: 'fashion-and-beauty'},
  {text: 'Film', value: 'film'},
  {text: 'Food & Drink', value: 'food-and-drink'},
  {text: 'Government & Politics', value: 'government-and-politics'},
  {text: 'Health & Wellness', value: 'health-and-wellness'},
  {text: 'Hobbies & Special Interest', value: 'hobbies-and-special-interest'},
  {text: 'Home & Lifestyle', value: 'home-and-lifstyle'},
  {text: 'Music', value: 'music'},
  {text: 'Outdoors', value: 'outdoors'},
  {text: 'Performing Arts', value: 'performing-arts'},
  {text: 'Religion & Spirituality', value: 'religion-and-spirituality'},
  {text: 'Science & Technology', value: 'science-and-technology'},
  {text: 'Seasonal & Holiday', value: 'seasonal-and-holiday'},
  {text: 'Sports & Fitness', value: 'sports-and-fitness'},
  {text: 'Travel', value: 'travel'},
  {text: 'Visual Arts', value: 'visual-arts'},
]