export const genreOptions = [
  {text: 'Alternative Country', value: 'alternative-country'},
  {text: 'Alternative Rock', value: 'alternative-rock'},
  {text: 'Ambient', value: 'ambient'},
  {text: 'Americana', value: 'americana'},
  {text: 'Avant-Garde', value: 'avant-garde'},
  {text: 'Bass', value: 'bass'},
  {text: 'Bluegrass', value: 'bluegrass'},
  {text: 'Blues', value: 'blues'},
  {text: 'Choral', value: 'choral'},
  {text: 'Classical', value: 'classical'},
  {text: 'Country', value: 'country'},
  {text: 'Dubstep', value: 'dubstep'},
  {text: 'Drum & Bass', value: 'drum-and-bass'},
  {text: 'Electronic', value: 'electronic'},
  {text: 'Experimental Rock', value: 'experimental-rock'},
  {text: 'Emo', value: 'emo'},
  {text: 'Folk', value: 'folk'},
  {text: 'Folk Punk', value: 'folk-punk'},
  {text: 'Funk', value: 'funk'},
  {text: 'Garage', value: 'garage'},
  {text: 'Glitch Hop', value: 'glitch-hop'},
  {text: 'Gospel', value: 'gospel'},
  {text: 'Grime', value: 'grime'},
  {text: 'Hardcore', value: 'hardcore'},
  {text: 'Hardcore / Punk', value: 'hardcore-punk'},
  {text: 'Hardstyle', value: 'hardstyle'},
  {text: 'Hard Rock', value: 'hard-rock'},
  {text: 'Hip Hop / Rap', value: 'hip-hop-rap'},
  {text: 'Holiday', value: 'holiday'},
  {text: 'House', value: 'house'},
  {text: 'IDM', value: 'idm'},
  {text: 'Indie Rock', value: 'indie-rock'},
  {text: 'Industrial', value: 'industrial'},
  {text: 'Jazz', value: 'jazz'},
  {text: 'Jam', value: 'jam'},
  {text: 'Latin', value: 'latin'},
  {text: 'Metal', value: 'metal'},
  {text: 'New Wave', value: 'new-wave'},
  {text: 'Opera', value: 'opera'},
  {text: 'Pop', value: 'pop'},
  {text: 'Punk', value: 'punk'},
  {text: 'R&B', value: 'r-and-b'},
  {text: 'Reggae', value: 'reggae'},
  {text: 'Reggaeton', value: 'reggaeton'},
  {text: 'Rock', value: 'rock'},
  {text: 'Shoegaze', value: 'shoegaze'},
  {text: 'Ska', value: 'ska'},
  {text: 'Soul', value: 'soul'},
  {text: 'Techno', value: 'techno'},
  {text: 'Trance', value: 'trance'},
  {text: 'Trap', value: 'trap'},
]